name: orbazacompose

services:
  postgres:
    build: .
    container_name: ORBaza
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: ORClient
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres

volumes:
  db_data:
